# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=30)),
                ('resto_location', models.CharField(max_length=30)),
                ('resto_speciality', models.CharField(max_length=30)),
                ('resto_image', models.ImageField(upload_to='photos/')),
                ('resto_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
